// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appcore} from '../models';

export function AcceptTruco():Promise<appcore.AppError>;

export function CloseSession():Promise<appcore.AppError>;

export function CreateHostSession(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<appcore.AppError>;

export function DispatchIntentJSON(arg1:string):Promise<appcore.AppError>;

export function JoinSession(arg1:string,arg2:string,arg3:string):Promise<appcore.AppError>;

export function NewHand():Promise<appcore.AppError>;

export function PlayCard(arg1:number):Promise<appcore.AppError>;

export function PlayFaceDownCard(arg1:number):Promise<appcore.AppError>;

export function PollEvents():Promise<Array<appcore.AppEvent>>;

export function RefuseTruco():Promise<appcore.AppError>;

export function RequestReplacementInvite(arg1:number):Promise<appcore.AppError>;

export function RequestTruco():Promise<appcore.AppError>;

export function Reset():Promise<appcore.AppError>;

export function RuntimeUpdateEventName():Promise<string>;

export function SendChat(arg1:string):Promise<appcore.AppError>;

export function SetLocale(arg1:string):Promise<appcore.AppError>;

export function Snapshot():Promise<appcore.SnapshotBundle>;

export function StartHostedMatch():Promise<appcore.AppError>;

export function StartOfflineGame(arg1:string,arg2:number):Promise<appcore.AppError>;

export function Tick(arg1:number):Promise<appcore.AppError>;

export function VoteHost(arg1:number):Promise<appcore.AppError>;
