// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptTruco() {
  return window['go']['main']['App']['AcceptTruco']();
}

export function CloseSession() {
  return window['go']['main']['App']['CloseSession']();
}

export function CreateHostSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateHostSession'](arg1, arg2, arg3, arg4, arg5);
}

export function DispatchIntentJSON(arg1) {
  return window['go']['main']['App']['DispatchIntentJSON'](arg1);
}

export function JoinSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['JoinSession'](arg1, arg2, arg3);
}

export function NewHand() {
  return window['go']['main']['App']['NewHand']();
}

export function PlayCard(arg1) {
  return window['go']['main']['App']['PlayCard'](arg1);
}

export function PollEvents() {
  return window['go']['main']['App']['PollEvents']();
}

export function RefuseTruco() {
  return window['go']['main']['App']['RefuseTruco']();
}

export function RequestReplacementInvite(arg1) {
  return window['go']['main']['App']['RequestReplacementInvite'](arg1);
}

export function RequestTruco() {
  return window['go']['main']['App']['RequestTruco']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function StartHostedMatch() {
  return window['go']['main']['App']['StartHostedMatch']();
}

export function StartOfflineGame(arg1, arg2) {
  return window['go']['main']['App']['StartOfflineGame'](arg1, arg2);
}

export function Tick(arg1) {
  return window['go']['main']['App']['Tick'](arg1);
}

export function VoteHost(arg1) {
  return window['go']['main']['App']['VoteHost'](arg1);
}
